// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  wikiSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome', // Overrides the default "intro" label
    },
    {
      type: 'category',
      label: 'Getting Started', // Displays as "Getting Started" instead of "getting-started"
      items: [
        {
          type: 'doc',
          id: 'getting-started/accounts',
          label: 'Requesting an Account', // Overrides "accounts"
        },
        {
          type: 'doc',
          id: 'getting-started/connecting',
          label: 'Connecting to the Cluster', // Overrides "connecting"
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware', // Overrides "hardware"
      items: [
        {
          type: 'doc',
          id: 'hardware/overview',
          label: 'Cluster Overview', // Overrides "overview"
        },
        {
          type: 'doc',
          id: 'hardware/storage',
          label: 'Storage Systems', // Overrides "storage"
        },
      ],
    },
    {
      type: 'category',
      label: 'Good Conduct',
      items: [
        {
          type: 'doc',
          id: 'good-conduct/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'good-conduct/login-nodes',
          label: 'Login Node Guidelines',
        },
        {
          type: 'doc',
          id: 'good-conduct/file-system',
          label: 'File System Practices',
        },
        {
          type: 'doc',
          id: 'good-conduct/job-submission',
          label: 'Job Submission Tips',
        },
        {
          type: 'doc',
          id: 'good-conduct/file-transfers',
          label: 'File Transfer Guide',
        },
      ],
    },
    {
      type: 'category',
      label: 'Software',
      items: [
        {
          type: 'doc',
          id: 'software/installed',
          label: 'Installed Software'
        },
        {
          type: 'doc',
          id: 'software/modules',
          label: 'Modules'
        },
        {
          type: 'doc',
          id: 'software/custom-install',
          label: 'Custom Install'
        }
      ]
    },
    {
      type: 'category',
      label: 'Support',
      items: [
        {
          type: 'doc',
          id: 'support/faq',
          label: 'FAQs'
        },
        {
          type: 'doc',
          id: 'support/contact',
          label: 'Getting Help'
        }
      ]
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'doc',
          id: 'tutorials/overview',
          label: 'Tutorials Overview'
        },
        {
          type: 'category',
          label: 'Linux Basics',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'tutorials/linux-basics/linux-intro',
              label: 'Introduction to Linux',
            },
          ],
        },
        {
        type: 'category',
        label: 'Running Slurm Jobs', // Displays as "Running Slurm Jobs" instead of "running-jobs"
        collapsed: true,
        items: [
        {
          type: 'doc',
          id: 'tutorials/running-jobs/slurm-basics',
          label: 'SLURM Basics', // Overrides "slurm-basics"
        },
        {
          type: 'doc',
          id: 'tutorials/running-jobs/job-scripts',
          label: 'Writing Job Scripts', // Overrides "job-scripts"
        },
        {
          type: 'doc',
          id: 'tutorials/running-jobs/sample-scripts',
          label: 'Sample SLURM Job Scripts'
        },
        {
          type: 'doc',
          id: 'tutorials/running-jobs/knl-nodes',
          label: 'Using KNL Node Features',
        },
        {
          type: 'doc',
          id: 'tutorials/running-jobs/troubleshooting',
          label: 'Troubleshooting Jobs', // Overrides "troubleshooting"
        },
        ],
        },
        {
          type: 'category',
          label: 'Containers',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'tutorials/containers/intro',
              label: 'Welcome to Containers @ ACE!'
            },
            {
              type: 'doc',
              id: 'tutorials/containers/containerize-code',
              label: 'Containerize Your Code'
            },
            {
              type: 'doc',
              id: 'tutorials/containers/containers-hpc',
              label: 'Containers on HPC Clusters'
            },
            {
              type: 'doc',
              id: 'tutorials/containers/advanced-builds',
              label: 'Advanced Build Topics'
            }
          ]
        },
      ]
    },
  ],
};

export default sidebars;
